sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: tdTT!_VzJq9dBNcV
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tHzX4fMjySKcCqKvYci
    access-key-secret: vPKhVa4Kux8jUP6FU4G14CQ3FW0wiC
    bucket-name: cangqiongwaimaipbj
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10